federal/urls.py
from django.conf.urls import url

from . import views
app_name = 'federal'

urlpatterns = [
    #thefederal/home
    url(r'^home/$',views.HomeView.as_view(), name = 'home'),

    #thefederal/index
    url(r'^$',views.index, name = 'index'),

    #thefederal/index
    url(r'^index/$',views.index, name = 'index'),

    #thefederal/sign_up
    url(r'^sign_up/$',views.SignupView.as_view() , name='signup'),

    #thefederal/sign_in
    url(r'^sign_in/$',views.SigninView.as_view() , name='signin'),

    #thefederal/signout
    url(r'logout/', views.logout, name='logout'),

    #thefederal/pk/comment
    url(r'^(?P<context_id>[0-9]+)/comment/$', views.CommentView.as_view(), name='comment'),

    #thefederal/pk/reply
    url(r'^(?P<context_id>[0-9]+)/reply/$', views.ReplyView.as_view(), name='reply'),

    #thefederal/ajax/validate_username
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),

    #thefederal/ajax/threadfavorited
    url(r'^ajax/t_favorited/$', views.t_favorited, name='t_favorited'),

    #thefederal/ajax/threadunfavorited
    url(r'^ajax/t_unfavorited/$', views.t_unfavorited, name='t_unfavorited'),

    #thefederal/ajax/commentfavorited
    url(r'^ajax/c_favorited/$', views.c_favorited, name='c_favorited'),

    #thefederal/ajax/commentunfavorited
    url(r'^ajax/c_unfavorited/$', views.c_unfavorited, name='c_unfavorited'),

    #thefederal/ajax/replyfavorited
    url(r'^ajax/r_favorited/$', views.r_favorited, name='r_favorited'),

    #thefederal/ajax/replyunfavorited
    url(r'^ajax/r_unfavorited/$', views.r_unfavorited, name='r_unfavorited'),

    #thefederal/favorites
    url(r'^favorites/$', views.favorites, name='favorites'),

    #thefederal/threadfavorite
    url(r'^threadfavorite/$', views.ThreadfavoriteView.as_view(), name='threadfavorite'),

    #thefederal/commentfavorite
    url(r'^commentfavorite/$', views.CommentfavoriteView.as_view(), name='commentfavorite'),

    #thefederal/replyfavorite
    url(r'^replyfavorite/$', views.ReplyfavoriteView.as_view(), name='replyfavorite'),

    #thefederal/profile
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

    #thefederal/feedback
    url(r'^feedback/$', views.FeedbackView.as_view(), name='feedback'),

    #thefederal/about
    url(r'^about/$', views.about, name='about'),

    #thefederal/terms
    url(r'^terms/$', views.terms, name='terms'),

    #thefederal/respect_policy
    url(r'^respect_policy/$', views.respect_policy, name='respect_policy'),

    #thefederal/content_policy
    url(r'^content_policy/$', views.content_policy, name='content_policy'),

    #thefederal/forgot_password
    url(r'^forgotpassword/$', views.ForgotPasswordView.as_view(), name='forgotpassword'),

    #thefederal/reset_password
    url(r'^resetpassword/$', views.ResetPasswordView.as_view(), name='resetpassword'),

    #thefederal/edit_profile
    url(r'^editprofile/$', views.EditProfileView.as_view(), name='editprofile'),

    #thefederal/state/w/all_json_models
    url(r'^state/(?P<state>[-\w]+)/all_json_models/$', views.all_json_models, name='all_json_models'),




]

thefederal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^ourfederal/', include('federal.urls')),
    url(r'^', include('federal.urls')),
    url(r'^admin/', admin.site.urls),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

federal/forms.py
from django.contrib.auth.models import User
from .models import Account , Feedback , ForgotPassword
from django import forms


class Signin(forms.ModelForm):

    username = forms.EmailField( widget=forms.TextInput(attrs={'placeholder': 'Email e.g you@gmail.com'}) )
    password = forms.CharField(max_length = 50,widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password']

class Signup(forms.ModelForm):

    firstname = forms.CharField(max_length = 30)
    lastname = forms.CharField(max_length = 30)
    username = forms.EmailField( widget=forms.TextInput(attrs={'placeholder': 'Email e.g you@gmail.com'}) )
    password = forms.CharField(max_length = 50,widget=forms.PasswordInput)
   
    class Meta:
        model = User
        fields = ['firstname','lastname','username','password']


class CommentTemplate(forms.ModelForm):

    comment = forms.CharField( widget=forms.TextInput(attrs={'placeholder': 'post comment here'}) )

    class Meta:
        model = User
        fields = ['comment']


class ReplyTemplate(forms.ModelForm):

    reply = forms.CharField( widget=forms.TextInput(attrs={'placeholder': 'post reply here'}) )

    class Meta:
        model = User
        fields = ['reply']


class ThreadTemplate(forms.ModelForm):

    thread = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    media = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True,
                                                                    'required': False}),required=False)

    def __init__(self, *args, **kwargs):
        super(ThreadTemplate, self).__init__(*args, **kwargs)
        self.fields['thread'].label = ""
        self.fields['media'].label = "Attach media"
        self.fields['thread'].widget.attrs = {'rows':6,
                                            'cols':30}
        self.fields['media'].widget.attrs = {'multiple' : True}

    class Meta:
        model = User
        fields = ['thread']




class ProfileTemplate(forms.ModelForm):

    class Meta:
        model = Account
        fields = ['display_pic']



class FeedbackTemplate(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['feed']


class FeedbackNewTemplate(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['firstname','lastname','feed']

class ForgotPasswordTemplate(forms.ModelForm):

    class Meta:
        model = ForgotPassword
        fields = ['username']

class ResetPasswordTemplate(forms.ModelForm):

    username = forms.EmailField( widget=forms.TextInput(attrs={'placeholder': 'Email e.g you@gmail.com'}) )
    reset_password = forms.IntegerField()

    class Meta:
        model = User
        fields = ['username','reset_password']



class EditProfileTemplate(forms.ModelForm):

    password = forms.CharField(max_length = 50,widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['password']

federal/views.py
from __future__ import unicode_literals
from django.views import generic
from django.views.generic import View
from django.contrib.auth.hashers import check_password , make_password
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate , login
from django.http import JsonResponse
from .forms import Signin , Signup , CommentTemplate , ReplyTemplate , ThreadTemplate , ProfileTemplate , FeedbackTemplate, FeedbackNewTemplate, ForgotPasswordTemplate , ResetPasswordTemplate, EditProfileTemplate
from .models import Account , State , Lga , Position , Thread ,Media , Zone , Comment , Reply , ThreadFavoriter, CommentFavoriter, ReplyFavoriter , Feedback , ForgotPassword
import random


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
VIDEO_FILE_TYPES = ['webm', 'mp4', 'ogg']


 
def index(request):

    if request.session.has_key('username'):
        username = request.session['username']

        return redirect( 'federal:home')



    thread_list = Thread.objects.filter(namespace = 999) | Thread.objects.filter(namespace = 990)

    content_cache = []
    content = {}

    for thread in thread_list:

        thread_post = thread.thread

        if len(thread_post.split()) >= 50:
            is_long = 1

        else:
            is_long = 0



        id = thread.id
        date = thread.date
        account_id = thread.account_id
        account = Account.objects.get(id=account_id)

        firstname = account.firstname
        lastname = account.lastname
        position_id = account.position_id
        display_pic = account.display_pic

        get_position = Position.objects.get(id = position_id)

        position = get_position.position

	favorite_count = ThreadFavoriter.objects.filter(id = id).count()

        comment_count = Comment.objects.filter(id = id).count()	

        thread_media = Media.objects.filter(thread_id = id)[:1]

        context_list = {
            'id' : id ,
            'thread_post' : thread_post,
            'date' : date,
            'is_long' : is_long,
            'thread_media': thread_media,
            'firstname' : firstname,
            'lastname' : lastname,
            'position' : position,
            'display_pic' : display_pic,
	    'favorite_count' : favorite_count,
	    'comment_count' : comment_count
        }

        content_cache.append(context_list)

    content = {
        'content_cache':content_cache
    }


    return render(request ,'federal/index.html',content)






class HomeView(FormView):

    form_class = ThreadTemplate
    template_name ='federal/home.html'
    is_logged_in = False
    show_form = False


    #audio_file = forms.FileField( label = _(u"Audio File" ))
    #video_file = forms.FileField( label = _(u"Video File" ))


    def get(self,request):

        if request.session.has_key('username'):
            username = request.session['username']
            is_logged_in = True
        else :
            is_logged_in = False

        account = Account.objects.get(username=username)

        a_position = account.position_id

        b_position = Position.objects.get(id = a_position)

        c_position = b_position.position

        if c_position == 'Citizen':
            show_form = False

        else :
            show_form = True

        zone_id = account.zone_id
        lga_id = account.lga_id
        state_id = account.state_id

        state = State.objects.get(id=state_id)
        state_code = state.state_code

        zone = Zone.objects.get(id=zone_id)
        zone_code = zone.zone_code

        lga = Lga.objects.get(id=lga_id)
        lga_code = lga.lga_code

        thread_list = Thread.objects.filter(namespace=999) | Thread.objects.filter(namespace=990) | \
                        Thread.objects.filter(state = state_code) | Thread.objects.filter(zone = zone_code) | \
                            Thread.objects.filter(lga = lga_code)



        content_cache = []
        content = {}

        for thread in thread_list:


            thread_post = thread.thread

            if len(thread_post.split()) >= 50:
                is_long = 1

            else:
                is_long = 0


            id = thread.id
            date = thread.date

            account_id = thread.account_id
            account = Account.objects.get(id=account_id)

            firstname = account.firstname
            lastname = account.lastname
            position_id = account.position_id
            display_pic = account.display_pic

            get_position = Position.objects.get(id = position_id)
            position = get_position.position

            my_id = Account.objects.get(username = username);
            my_id = my_id.id

            if_favorited = ThreadFavoriter.objects.filter(thread_id = id , account_id = my_id).exists()

            favorite_count = ThreadFavoriter.objects.filter(id = id).count()

	    comment_count = Comment.objects.filter(id = id).count()

            thread_media = Media.objects.filter(thread_id = id)[:1]

            context_list = {
                'id' : id,
                'thread_post' : thread_post,
                'date' : date,
                'is_long' : is_long,
                'thread_media' : thread_media,
                'firstname' : firstname,
                'lastname' : lastname,
                'position' : position,
                'display_pic' : display_pic,
                'if_favorited' : if_favorited,
                'favorite_count' : favorite_count,
		'comment_count' : comment_count 
            }

            content_cache.append(context_list)

        form=self.form_class(None)

        content = {
            'form' : form,
            'content_cache':content_cache,
            'show_form' : show_form,
            'is_logged_in' : is_logged_in
        }


        return render(request ,self.template_name,content)



    def post(self,request , *args, **kwargs):

        if request.session.has_key('username'):
            username = request.session['username']
            is_logged_in = True
        else :
            is_logged_in = False

        err_msg = ''

        #form=self.form_class(request)
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        media = request.FILES.getlist('media')

        if form.is_valid():


            thread = form.cleaned_data['thread']

            new_thread = Thread()

            account = Account.objects.get(username=username)

            state_id = account.state_id
            zone_id = account.zone_id
            lga_id = account.lga_id

            account_id = account.id
            position_id = account.position_id
            a_position = position_id


            b_position = Position.objects.get(id = a_position)

            c_position = b_position.position

            if c_position == 'Citizen':
                show_form = False

            else :
                show_form = True

            position = Position.objects.get(id=position_id)

            namespace = 0
            state = 0
            zone = 0
            lga = 0

            if position.namespace != 0:
                namespace = position.namespace

            elif position.state != 0:
                state = position.state

            elif position.zone != 0:
                zone = position.zone

            elif position.lga != 0:
                lga = position.lga

            else:
                pass

            new_thread.thread = thread
            new_thread.account = account
            new_thread.namespace = namespace
            new_thread.state = state
            new_thread.zone = zone
            new_thread.lga = lga

            new_thread.save()

            thread_id = new_thread.id

            thread = Thread.objects.get(id=thread_id)

            for m in media :

                media_register = Media()
                media_register.thread = thread

                media_register.image = m
                media_register.audio = m
                media_register.video = m

                file_type = media_register.image.url.split('.')[-1]
                file_type = file_type.lower()

                if file_type in IMAGE_FILE_TYPES:

                    media_register.audio = 0
                    media_register.video = 0

                else:

                    file_type = media_register.audio.url.split('.')[-1]
                    file_type = file_type.lower()

                    if file_type in AUDIO_FILE_TYPES:

                        media_register.image = 0
                        media_register.video = 0

                    else:

                        file_type = media_register.video.url.split('.')[-1]
                        file_type = file_type.lower()

                        if file_type in VIDEO_FILE_TYPES:

                            media_register.image = 0
                            media_register.audio = 0

                        else:
                            err_msg = 'Unsupported file format, file should be valid image, audio or/and video files'




                media_register.save()








            state = State.objects.get(id=state_id)
            state_code = state.state_code

            zone = Zone.objects.get(id=zone_id)
            zone_code = zone.zone_code

            lga = Lga.objects.get(id=lga_id)
            lga_code = lga.lga_code

            thread_list = Thread.objects.filter(namespace=999) | Thread.objects.filter(namespace=990) | \
                            Thread.objects.filter(state = state_code) | Thread.objects.filter(zone = zone_code) | \
                                Thread.objects.filter(lga = lga_code)



            content_cache = []
            content = {}

federal/templates/federal/base.html
<!DOCTYPE html>
<html lang = "en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Our Federal{% endblock %}</title>
  {% load staticfiles %}
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width = device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css"  href="{% static 'federal/style.css' %}" />
  <link href='https://fonts.googleapis.com/css?family=Satisfy'
  rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 
  <style>

body{
  background-color: green;
}

.navbar {
    border-radius: 0;
    border-style: none;
}

.navbar {
    background: rgba(225, 225, 225, 0.9)
}

.navbar-default .navbar-brand {
    color: green;
}

.navbar-brand {
  color:green;
}

.thread-post{
    background-color: white;
}

.badge-info{
    background-color:orange;
}

.comment_thread{
   background: whitesmoke;
   padding : 10px;

}

.reply_thread{
    background: whitesmoke;
    padding : 10px;
}

</style>


</head>

<body>
        <nav class ="navbar navbar-default navbar-fixed-top" role="navigation">

                    <div class="#">
                      {% block home %}
                       <a class="navbar-brand" href="{% url 'federal:home' %}">Our Federal</a>
                        {% endblock %}

                        <div style="text-align:right;padding-right:15px;">
                          <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-list" style="color:green;font-size:1.3em;"><span>
                              </a>
                              <ul class="dropdown-menu">
                                {% block signout %}
                                 <li><a href = "{% url 'federal:profile' %}"><span style="color:black;">Profile</span></a></li>
                                 <li><a href = "{% url 'federal:favorites' %}"><span style="color:black;">Favorites</span></a></li>
                                 <li><a href = "{% url 'federal:about' %}"><span style="color:black;">About</span></a></li>
                                 <li><a href = "{% url 'federal:feedback' %}"><span style="color:black;">Feedback</span></a></li>
                                 <li><a href = "{% url 'federal:logout' %}"><span style="color:black;">Signout</span></a></li>
                                 {% endblock %}
                              </ul>
                            </li>
                          </ul>
                        </div>

                      </div>
            </nav><br /><br /><br /><br />
            {% block body %}
            {% endblock %}

            {% block javascript %}{% endblock %}
</body>
</html>

federal/templates/federal/content_policy.html
{% extends 'federal/base.html'  %}
{% block title %}The Federal Content Policy{% endblock %}
{% block home %} <a class="navbar-brand" href="{% url 'federal:index' %}">The Federal</a> {% endblock %}
{% block signout %}
<li><a href= "{% url 'federal:signin' %}"><span style="color:black;">Sign In</span></a></li>
<li><a href= "{% url 'federal:about' %}"><span style="color:black;">About</span></a></li>
{% endblock %}

{% block body %}

<div class="container">
        <div class="row">
          <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-12 col-xs-12">

                <div class="panel panel-default">
                        <div class="panel-body">

          <p style="font-size:1.5em;color:green;text-align:center;">The Federal</p>
          <p  style="font-size:1.2em;color:orange;text-align:center;">Content Policy</p>

                        </div></div>

        </div>
    </div>
</div>
{% endblock %}

federal/templates/federal/index.html
{% extends 'federal/base.html'  %}

{% block javascript %}
  <script>
    $(".no-favorite").click(function () {

      alert('Sorry you have to login to favorite this post');

    });


    $(".no-comment").click(function () {

      alert('Sorry you have to login to comment on this post');

    });
  </script>
{% endblock %}


{% block home %} <a class="navbar-brand" href="{% url 'federal:index' %}">Our Federal</a> {% endblock %}
{% block signout %}
<li><a href= "{% url 'federal:signin' %}"><span style="color:black;">Sign In</span></a></li>
<li><a href= "{% url 'federal:about' %}"><span style="color:black;">About</span></a></li>
{% endblock %}
{% block body %}
{% if content_cache %}

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
      <p style="text-align:center;font-size:1.3em;color:white;">Democracy</p>


 <ul>
    {% for context in content_cache %}

    <div class="panel panel-default">
        <div class="panel-body">

        <p style="color:green;font-size:.9em;"><img src="{{ context.display_pic.url }}" alt="Profile picture" height="50px" width="50px">
          {{ context.firstname|escape }} {{ context.lastname|escape }} </p>
        <p style="color:green;font-size:.9em;">{{ context.position|escape }}</p>
        <p style="color:grey;font-size:.9em;"> {{ context.date|date:"D d M Y g:i a"|escape }} </p>

         {% if context.is_long %}
           <p>{{ context.thread_post|safe|truncatewords:"50"|linebreaks|escape }}</p>
           <a href="{% url 'federal:comment' context.id %}">read more</a>
         {% else %}
           <p>{{ context.thread_post|safe|linebreaks|escape }}</p><hr />
         {% endif %}

         {% if context.thread_media %}
          {% for media in context.thread_media %}

            {% if media.image|length > 1 %}
            <p><img src="{{ media.image.url }}" alt="image" style='height: 100%; width: 100%; object-fit: contain'></p><br />
            {% elif media.audio|length > 1 %}
            <p><audio width = "200" height = "100" controls style='height: 100%; width: 100%; object-fit: contain'>
              <source src = "{{ media.audio.url|escape }}" type="audio/ogg">
              <source src = "{{ media.audio.url|escape }}" type="audio/mpeg">
              <source src = "{{ media.audio.url|escape }}"type="audio/wav">
                Sorry your browser does not support the audio element
            <audio></p><br />
            {% elif media.video|length > 1 %}
            <p><video width="500" height="260" preload controls style='height: 100%; width: 100%; object-fit: contain'>
              <source src="{{ media.video.url|escape }}" type="video/mp4; "/>
              <source src="{{ media.video.url|escape }}" type="video/ogg; "/>
              <source src="{{ media.video.url|escape }}" type="video/webm "/>
                Sorry your browser does not support the video tag yet
           </video></p><br />
            {% else %}
              <p>Oops something happened, media could not be loaded</p>
            {% endif %}

          {% endfor %}
        {% endif %}

        <p><a href="#" class="no-favorite">favorite</a>
	   <span class="badge badge-info favorite-count">{{ context.favorite_count|escape }}</span>
            <a href="#" class="no-comment">comment</a>
	             <span class="badge badge-info favorite-count">{{ context.comment_count|escape }}</span>
              share to

		{% load social_share %}

              {% post_to_facebook object_or_url "facebook" %} |
              {% post_to_twitter "From OurFederal: Read more" object_or_url "twitter" %}

		</p><hr />

      </div>
    </div>
    {% endfor %}

</ul>
{% else %}
    <h3>You don't have any New threads </h3>
  </div></div></div>
{% endif %}

{% endblock %}

federal/templates/federal/sign_in.html
{% extends 'federal/base.html'  %}
{% block title %}Our Federal Signin{% endblock %}
{% block home %} <a class="navbar-brand" href="{% url 'federal:signin' %}">Our Federal</a> {% endblock %}
{% block signout %}
<li><a href= "{% url 'federal:signup' %}"><span style="color:black;">Sign Up</span></a></li>
<li><a href= "{% url 'federal:about' %}"><span style="color:black;">About</span></a></li>
{% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-sm-offset-2 col-sm-10">
                  <p style="text-align:center;color:green;font-size:1.3em;">SIGN IN</p>
                </div>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'federal/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">sign in</button>
                        </div>
                    </div>

                    <div class="col-sm-offset-2 col-sm-10">
                    {% if err_msg %}
                    <p class="text-danger">{{ err_msg }}</p>
                    {% endif %}
                  </div>

                    </form>

                    <div class="col-sm-offset-2 col-sm-10">
                    <a href="/ourfederal/sign_up">Sign Up</a>
                  </div>
                  <p style="text-align:center;color:grey;">
                  <a href="{% url 'federal:forgotpassword' %}">Forgot Password ?</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

federal/templates/federal/sign_up.html
{% extends 'federal/base.html'  %}

{% block home %} <a class="navbar-brand" href="{% url 'federal:home' %}">Our Federal</a> {% endblock %}
{% block signout %}
 <li><a href= "{% url 'federal:signin' %}"><span style="color:black;">Sign In</span></a></li>
 <li><a href= "{% url 'federal:about' %}"><span style="color:black;">About</span></a></li>
 {% endblock %}

{% block javascript %}
  <script>
    $("#id_username").change(function () {
      //alert("Control reached here");
      var username = $(this).val();

      //alert("Control reached here " + username);

      $.ajax({
        url: '/ourfederal/ajax/validate_username/',
        data: {
          'username': username
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert("A user with this username already exists.");
          }
        },

        error : function(data) {
           alert("A bug appeared.");
           console.log(); // provide a bit more info about the error to the console
       }

      });

    });



$(document).ready(
   function() {
     $("select#state").change(function() {
       if ($(this).val() == 'Z') {
         $("select#lga").html("<option>Select a lga</option>");
         $("select#lga").attr('disabled', true);
    }
       else {
         var url = "/state/" + $(this).val() + "/all_json_models";
         var brand = $(this).val();
    $.getJSON(url, function(models) {
      var options = '<option value="Z">Select a lga</option>';
      for (var i = 0; i < models.length; i++) {
        options += '<option value="' + models[i].pk + '">' + models[i].fields['lga'] + '</option>';
    }
      $("select#lga").html(options);
      $("select#lga option:first").attr('selected', 'selected');
      $("select#lga").attr('disabled', false);
    });
    }
    });


    $("select#state").change(function(vent) {
      if ($(this).val() == -1) {
        return;
    }
    //myAwesomeFunctionToCallWhenAModelIsSelected();
    });
    });



  </script>
{% endblock %}

{% block title %}Our Federal Signup{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                  <div class="col-sm-offset-2 col-sm-10">
                  <p style="text-align:center;color:green;font-size:1.5em;">SIGN UP</p>
                  <p style="text-align:center;color:green;">Create an account</p>
                </div>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'federal/form-template.html' %}

		    <div class="form-group">
                                  <div class="col-sm-offset-2 col-sm-10">
                                    <label id="confirm_password">Confirm Password</label>
                                      <input type="password" name="confirm_password">
                                  </div>
                              </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                      <select name="state" id="state">
                        <option value="Z">Select a state</option>
                        {% for state in state_list %}
                        <option value="{{ state.id }}">{{ state.state}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    </div>



                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                      <select name="lga" id="lga" disabled="true">
                      <option>Select a lga</option>
                      </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Create an Account</button>
                        </div>
                    </div>

                    <div class="col-sm-offset-2 col-sm-10">
                    {% if err_msg %}
                    <p class="text-danger">{{ err_msg }}</p>
                    {% endif %}
                  </div>

                    </form>

                    <div class="col-sm-offset-2 col-sm-10">
                    <a href="/ourfederal/sign_in">Sign In</a>
                  </div>

                    <p style="text-align:center;color:grey;">By signing up, you agree to our
                    <a href="{% url 'federal:terms' %}">Terms</a> and that you have read our
                    <a href="{% url 'federal:respect_policy' %}">Respect Policy</a> and <a href="{% url 'federal:content_policy' %}"> Content Policy.</a></p>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}